name: Cypress Tests

on: 
  - push
  - pull_request

jobs:
   cypress-run:
     runs-on: ubuntu-22.04

     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Install Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 22
 
       - name: Install PNPM
         uses: pnpm/action-setup@v4
         with:
           version: 10
           run_install: false
 
       - name: Get pnpm store directory
         shell: bash
         run: |
           STORE_PATH=$(pnpm store path --silent)
           echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
           echo "STORE_PATH=$STORE_PATH"
           export STORE_PATH
   
       - uses: actions/cache@v4
         name: Setup pnpm cache
         env:
           STORE_PATH: ${{ env.STORE_PATH }}
         with:
           path: ${{ env.STORE_PATH }}
           key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
           restore-keys: |
             ${{ runner.os }}-pnpm-store-
 
       - name: Install dependencies
         run: pnpm install
 
       - name: Cypress run
         uses: cypress-io/github-action@v6
         env: 
           APP_URL: "http://localhost:3000"
           NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api.vercel.app"
         with:
           build: npm run build
           start: npm start